"""
crear_bases.py
Crea las bases de datos + tablas en Oracle, PostgreSQL y MySQL
100% Python puro - SIN ARCHIVOS SQL
"""

import os
import oracledb
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import mysql.connector


# === CONEXIONES ===
def oracle_sys_conn():
    return oracledb.connect(
        user="system",
        password="root",
        dsn="localhost/XE",
    )


def pg_admin_conn():
    return psycopg2.connect(
        host="localhost",
        user="postgres",
        password="root",
        dbname="postgres",
    )


def mysql_root_conn():
    return mysql.connector.connect(
        host="localhost",
        user="root",
        password="root",
    )


# === ORACLE ===
def crear_oracle():
    print("\nORACLE: Creando usuario y esquema...")
    conn = oracle_sys_conn()
    cursor = conn.cursor()

    user = "gestion_practicas"
    password = "gestion123"

    try:
        cursor.execute(f"DROP USER gestion_practicas CASCADE")
        print("Usuario anterior eliminado")
    except:
        pass

    cursor.execute(f"CREATE USER gestion_practicas IDENTIFIED BY gestion123")
    cursor.execute(f"GRANT CONNECT, RESOURCE, DBA TO gestion_practicas")
    cursor.execute(f"GRANT UNLIMITED TABLESPACE TO gestion_practicas")
    print("Usuario creado con permisos")

    # Conectar como usuario nuevo
    conn.close()
    conn = oracledb.connect(user=user, password=password, dsn="localhost/XE")
    cursor = conn.cursor()

    print("Creando tablas en Oracle...")
    cursor.execute(
        """
        CREATE TABLE CENTROS_EDUCATIVOS (
            id_centro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            direccion VARCHAR2(200),
            provincia VARCHAR2(50),
            tipo_centro VARCHAR2(50)
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE EMPRESAS (
            id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            sector VARCHAR2(50),
            direccion VARCHAR2(200),
            ciudad VARCHAR2(50),
            persona_contacto VARCHAR2(100),
            correo_contacto VARCHAR2(100),
            telefono VARCHAR2(20),
            satisfaccion_media NUMBER(3,2)
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE ESTUDIANTES (
            id_estudiante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dni VARCHAR2(9) UNIQUE NOT NULL,
            nombre VARCHAR2(100) NOT NULL,
            correo VARCHAR2(100),
            telefono VARCHAR2(20),
            id_centro NUMBER REFERENCES CENTROS_EDUCATIVOS(id_centro),
            titulacion VARCHAR2(100),
            curso_academico VARCHAR2(20),
            nacionalidad VARCHAR2(50),
            fecha_nacimiento DATE
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE TUTORES (
            id_tutor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre VARCHAR2(100) NOT NULL,
            correo VARCHAR2(100),
            id_centro NUMBER REFERENCES CENTROS_EDUCATIVOS(id_centro),
            especialidad VARCHAR2(100)
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE CONVENIOS (
            id_convenio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_empresa NUMBER REFERENCES EMPRESAS(id_empresa),
            id_centro NUMBER REFERENCES CENTROS_EDUCATIVOS(id_centro),
            fecha_inicio DATE,
            fecha_fin DATE,
            observaciones CLOB
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE PRACTICAS (
            id_practica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_estudiante NUMBER REFERENCES ESTUDIANTES(id_estudiante),
            id_tutor NUMBER REFERENCES TUTORES(id_tutor),
            id_empresa NUMBER REFERENCES EMPRESAS(id_empresa),
            id_convenio NUMBER REFERENCES CONVENIOS(id_convenio),
            fecha_inicio DATE,
            fecha_fin DATE,
            horas_totales NUMBER,
            estado VARCHAR2(20),
            evaluacion_final NUMBER(3,2)
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE REGISTROS_ACTIVIDAD (
            id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_practica NUMBER REFERENCES PRACTICAS(id_practica),
            fecha DATE,
            descripcion CLOB,
            horas NUMBER,
            validado_por_tutor CHAR(1) DEFAULT '0'
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE EVALUACIONES (
            id_evaluacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_practica NUMBER REFERENCES PRACTICAS(id_practica),
            tipo VARCHAR2(20),
            fecha DATE,
            puntuacion NUMBER(3,2),
            comentarios CLOB
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE INCIDENCIAS (
            id_incidencia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_practica NUMBER REFERENCES PRACTICAS(id_practica),
            fecha DATE,
            descripcion CLOB,
            tipo VARCHAR2(20),
            resuelta CHAR(1) DEFAULT '0'
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE DOCUMENTOS (
            id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_practica NUMBER REFERENCES PRACTICAS(id_practica),
            tipo VARCHAR2(20),
            nombre_archivo VARCHAR2(200),
            ruta_archivo VARCHAR2(500),
            tamano NUMBER
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE INDICADORES_ANALITICOS (
            id_indicador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_empresa NUMBER REFERENCES EMPRESAS(id_empresa),
            id_centro NUMBER REFERENCES CENTROS_EDUCATIVOS(id_centro),
            anio NUMBER(4),
            practicas_realizadas NUMBER,
            tasa_finalizacion NUMBER(5,2),
            satisfaccion_media NUMBER(3,2),
            tasa_contratacion NUMBER(5,2),
            abandonos NUMBER
        )
    """
    )

    cursor.execute(
        """
        CREATE TABLE LOGS_SISTEMA (
            id_log NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_usuario NUMBER,
            tipo_evento VARCHAR2(50),
            detalle CLOB,
            ip VARCHAR2(45)
        )
    """
    )

    conn.commit()
    print("TODAS LAS TABLAS CREADAS EN ORACLE")
    cursor.close()
    conn.close()


# === POSTGRESQL ===
# === POSTGRESQL ===
# === POSTGRESQL ===
def crear_postgresql():
    print("\nPOSTGRESQL: Creando base de datos y tablas...")
    conn = pg_admin_conn()
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    cursor = conn.cursor()

    db_name = "gestion_practicas"
    cursor.execute(f"DROP DATABASE IF EXISTS {db_name}")
    cursor.execute(f"CREATE DATABASE {db_name}")
    cursor.close()
    conn.close()

    conn = psycopg2.connect(
        host="localhost",
        user="postgres",
        password="root",
        dbname=db_name,
    )
    cursor = conn.cursor()

    # 1️⃣ Tablas base
    cursor.execute(
        """
        CREATE TABLE CENTROS_EDUCATIVOS (
            id_centro SERIAL PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            direccion TEXT,
            provincia VARCHAR(50),
            tipo_centro VARCHAR(50)
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE EMPRESAS (
            id_empresa SERIAL PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            sector VARCHAR(50),
            direccion TEXT,
            ciudad VARCHAR(50),
            persona_contacto VARCHAR(100),
            correo_contacto VARCHAR(100),
            telefono VARCHAR(20),
            satisfaccion_media DECIMAL(3,2)
        )
    """
    )

    # 2️⃣ Tablas dependientes de CENTROS_EDUCATIVOS
    cursor.execute(
        """
        CREATE TABLE ESTUDIANTES (
            id_estudiante SERIAL PRIMARY KEY,
            dni VARCHAR(9) UNIQUE NOT NULL,
            nombre VARCHAR(100) NOT NULL,
            correo VARCHAR(100),
            telefono VARCHAR(20),
            id_centro INT REFERENCES CENTROS_EDUCATIVOS(id_centro),
            titulacion VARCHAR(100),
            curso_academico VARCHAR(20),
            nacionalidad VARCHAR(50),
            fecha_nacimiento DATE
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE TUTORES (
            id_tutor SERIAL PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            correo VARCHAR(100),
            id_centro INT REFERENCES CENTROS_EDUCATIVOS(id_centro),
            especialidad VARCHAR(100)
        )
    """
    )

    # 3️⃣ Tablas dependientes de EMPRESAS y CENTROS_EDUCATIVOS
    cursor.execute(
        """
        CREATE TABLE CONVENIOS (
            id_convenio SERIAL PRIMARY KEY,
            id_empresa INT REFERENCES EMPRESAS(id_empresa),
            id_centro INT REFERENCES CENTROS_EDUCATIVOS(id_centro),
            fecha_inicio DATE,
            fecha_fin DATE,
            observaciones TEXT
        )
    """
    )

    # 4️⃣ PRACTICAS
    cursor.execute(
        """
        CREATE TABLE PRACTICAS (
            id_practica SERIAL PRIMARY KEY,
            id_estudiante INT REFERENCES ESTUDIANTES(id_estudiante) ON DELETE CASCADE,
            id_tutor INT REFERENCES TUTORES(id_tutor) ON DELETE SET NULL,
            id_empresa INT REFERENCES EMPRESAS(id_empresa) ON DELETE CASCADE,
            id_convenio INT REFERENCES CONVENIOS(id_convenio) ON DELETE CASCADE,
            fecha_inicio DATE,
            fecha_fin DATE,
            horas_totales INT,
            estado VARCHAR(20),
            evaluacion_final DECIMAL(3,2)
        )
    """
    )

    # 5️⃣ Tablas dependientes de PRACTICAS
    cursor.execute(
        """
        CREATE TABLE REGISTROS_ACTIVIDAD (
            id_registro SERIAL PRIMARY KEY,
            id_practica INT REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE,
            fecha DATE,
            descripcion TEXT,
            horas INT,
            validado_por_tutor BOOLEAN DEFAULT FALSE
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE EVALUACIONES (
            id_evaluacion SERIAL PRIMARY KEY,
            id_practica INT REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE,
            tipo VARCHAR(20),
            fecha DATE,
            puntuacion DECIMAL(3,2),
            comentarios TEXT
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE INCIDENCIAS (
            id_incidencia SERIAL PRIMARY KEY,
            id_practica INT REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE,
            fecha DATE,
            descripcion TEXT,
            tipo VARCHAR(20),
            resuelta BOOLEAN DEFAULT FALSE
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE DOCUMENTOS (
            id_documento SERIAL PRIMARY KEY,
            id_practica INT REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE,
            tipo VARCHAR(20),
            nombre_archivo VARCHAR(200),
            ruta_archivo VARCHAR(500),
            tamano INT
        )
    """
    )

    # 6️⃣ Tablas independientes de PRACTICAS pero con FK a EMPRESAS/CENTROS_EDUCATIVOS
    cursor.execute(
        """
        CREATE TABLE INDICADORES_ANALITICOS (
            id_indicador SERIAL PRIMARY KEY,
            id_empresa INT REFERENCES EMPRESAS(id_empresa) ON DELETE SET NULL,
            id_centro INT REFERENCES CENTROS_EDUCATIVOS(id_centro) ON DELETE SET NULL,
            anio INT,
            practicas_realizadas INT,
            tasa_finalizacion DECIMAL(5,2),
            satisfaccion_media DECIMAL(5,2),
            tasa_contratacion DECIMAL(5,2),
            abandonos INT
        )
    """
    )
    cursor.execute(
        """
        CREATE TABLE LOGS_SISTEMA (
            id_log SERIAL PRIMARY KEY,
            id_usuario INT,
            tipo_evento VARCHAR(50),
            detalle TEXT,
            ip VARCHAR(45)
        )
    """
    )

    conn.commit()
    print("TODAS LAS TABLAS CREADAS EN POSTGRESQL")
    cursor.close()
    conn.close()


# === MYSQL ===
# === MYSQL ===
def crear_mysql():
    print("\nMYSQL: Creando base de datos y tablas...")
    conn = mysql_root_conn()
    cursor = conn.cursor()

    db_name = "gestion_practicas"
    cursor.execute(f"DROP DATABASE IF EXISTS {db_name}")
    cursor.execute(
        f"CREATE DATABASE {db_name} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
    )
    cursor.execute(f"USE {db_name}")

    # 1️⃣ Tablas base
    cursor.execute(
        """
        CREATE TABLE CENTROS_EDUCATIVOS (
            id_centro INT AUTO_INCREMENT PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            direccion TEXT,
            provincia VARCHAR(50),
            tipo_centro VARCHAR(50)
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE EMPRESAS (
            id_empresa INT AUTO_INCREMENT PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            sector VARCHAR(50),
            direccion TEXT,
            ciudad VARCHAR(50),
            persona_contacto VARCHAR(100),
            correo_contacto VARCHAR(100),
            telefono VARCHAR(20),
            satisfaccion_media DECIMAL(3,2)
        ) ENGINE=InnoDB
    """
    )

    # 2️⃣ Tablas dependientes de CENTROS_EDUCATIVOS
    cursor.execute(
        """
        CREATE TABLE ESTUDIANTES (
            id_estudiante INT AUTO_INCREMENT PRIMARY KEY,
            dni VARCHAR(9) UNIQUE NOT NULL,
            nombre VARCHAR(100) NOT NULL,
            correo VARCHAR(100),
            telefono VARCHAR(20),
            id_centro INT,
            titulacion VARCHAR(100),
            curso_academico VARCHAR(20),
            nacionalidad VARCHAR(50),
            fecha_nacimiento DATE,
            FOREIGN KEY (id_centro) REFERENCES CENTROS_EDUCATIVOS(id_centro)
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE TUTORES (
            id_tutor INT AUTO_INCREMENT PRIMARY KEY,
            nombre VARCHAR(100) NOT NULL,
            correo VARCHAR(100),
            id_centro INT,
            especialidad VARCHAR(100),
            FOREIGN KEY (id_centro) REFERENCES CENTROS_EDUCATIVOS(id_centro)
        ) ENGINE=InnoDB
    """
    )

    # 3️⃣ Tablas dependientes de EMPRESAS y CENTROS_EDUCATIVOS
    cursor.execute(
        """
        CREATE TABLE CONVENIOS (
            id_convenio INT AUTO_INCREMENT PRIMARY KEY,
            id_empresa INT,
            id_centro INT,
            fecha_inicio DATE,
            fecha_fin DATE,
            observaciones TEXT,
            FOREIGN KEY (id_empresa) REFERENCES EMPRESAS(id_empresa),
            FOREIGN KEY (id_centro) REFERENCES CENTROS_EDUCATIVOS(id_centro)
        ) ENGINE=InnoDB
    """
    )

    # 4️⃣ PRACTICAS
    cursor.execute(
        """
        CREATE TABLE PRACTICAS (
            id_practica INT AUTO_INCREMENT PRIMARY KEY,
            id_estudiante INT,
            id_tutor INT,
            id_empresa INT,
            id_convenio INT,
            fecha_inicio DATE,
            fecha_fin DATE,
            horas_totales INT,
            estado VARCHAR(20),
            evaluacion_final DECIMAL(3,2),
            FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTES(id_estudiante),
            FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor),
            FOREIGN KEY (id_empresa) REFERENCES EMPRESAS(id_empresa),
            FOREIGN KEY (id_convenio) REFERENCES CONVENIOS(id_convenio)
        ) ENGINE=InnoDB
    """
    )

    # 5️⃣ Tablas dependientes de PRACTICAS
    cursor.execute(
        """
        CREATE TABLE REGISTROS_ACTIVIDAD (
            id_registro INT AUTO_INCREMENT PRIMARY KEY,
            id_practica INT,
            fecha DATE,
            descripcion TEXT,
            horas INT,
            validado_por_tutor TINYINT(1) DEFAULT 0,
            FOREIGN KEY (id_practica) REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE EVALUACIONES (
            id_evaluacion INT AUTO_INCREMENT PRIMARY KEY,
            id_practica INT,
            tipo VARCHAR(20),
            fecha DATE,
            puntuacion DECIMAL(3,2),
            comentarios TEXT,
            FOREIGN KEY (id_practica) REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE INCIDENCIAS (
            id_incidencia INT AUTO_INCREMENT PRIMARY KEY,
            id_practica INT,
            fecha DATE,
            descripcion TEXT,
            tipo VARCHAR(20),
            resuelta TINYINT(1) DEFAULT 0,
            FOREIGN KEY (id_practica) REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE DOCUMENTOS (
            id_documento INT AUTO_INCREMENT PRIMARY KEY,
            id_practica INT,
            tipo VARCHAR(20),
            nombre_archivo VARCHAR(200),
            ruta_archivo VARCHAR(500),
            tamano INT,
            FOREIGN KEY (id_practica) REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
        ) ENGINE=InnoDB
    """
    )

    # 6️⃣ Tablas independientes de PRACTICAS
    cursor.execute(
        """
        CREATE TABLE INDICADORES_ANALITICOS (
            id_indicador INT AUTO_INCREMENT PRIMARY KEY,
            id_empresa INT,
            id_centro INT,
            anio INT,
            practicas_realizadas INT,
            tasa_finalizacion DECIMAL(5,2),
            satisfaccion_media DECIMAL(5,2),
            tasa_contratacion DECIMAL(5,2),
            abandonos INT,
            FOREIGN KEY (id_empresa) REFERENCES EMPRESAS(id_empresa),
            FOREIGN KEY (id_centro) REFERENCES CENTROS_EDUCATIVOS(id_centro)
        ) ENGINE=InnoDB
    """
    )
    cursor.execute(
        """
        CREATE TABLE LOGS_SISTEMA (
            id_log INT AUTO_INCREMENT PRIMARY KEY,
            id_usuario INT,
            tipo_evento VARCHAR(50),
            detalle TEXT,
            ip VARCHAR(45)
        ) ENGINE=InnoDB
    """
    )

    conn.commit()
    print("TODAS LAS TABLAS CREADAS EN MYSQL")
    cursor.close()
    conn.close()


# === MAIN ===
if __name__ == "__main__":
    print("\n" + "=" * 80)
    print("CREANDO BASES DE DATOS + TABLAS (100% PYTHON PURO)")
    print("=" * 80 + "\n")

    ORACLE_ACTIVE = True
    PG_ACTIVE = True
    MYSQL_ACTIVE = True

    if ORACLE_ACTIVE:
        crear_oracle()
    if PG_ACTIVE:
        crear_postgresql()
    if MYSQL_ACTIVE:
        crear_mysql()

    print("\n¡3 BASES DE DATOS + TABLAS CREADAS CON ÉXITO!")
    print("Ejecuta ahora: python seed.py")
