-- ============================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS (Oracle)
-- Sistema de Gestión de Prácticas Educativas
-- ============================================

-- ============================================
-- 0️⃣ LIMPIEZA PREVIA (Ejecutar como SYSDBA)
-- ============================================

-- Eliminar el usuario y todos sus objetos en cascada
-- (Ignorar error si no existe)
DECLARE
    usuario_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO usuario_existe 
    FROM dba_users 
    WHERE username = 'GESTION_PRACTICAS';
    
    IF usuario_existe > 0 THEN
        EXECUTE IMMEDIATE 'DROP USER gestion_practicas CASCADE';
    END IF;
END;
--/

-- ============================================
-- 1️⃣ Crear usuario y esquema
-- ============================================

CREATE USER gestion_practicas IDENTIFIED BY gestion123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO gestion_practicas;

ALTER SESSION SET CURRENT_SCHEMA = gestion_practicas;

-- ============================================
-- 2️⃣ CREACIÓN DE TABLAS
-- ============================================

-- Tabla de Centros Educativos
CREATE TABLE CENTROS_EDUCATIVOS (
    id_centro NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(255),
    provincia VARCHAR2(100),
    tipo_centro VARCHAR2(100),
    CONSTRAINT pk_centros_educativos PRIMARY KEY (id_centro),
    CONSTRAINT nn_centros_nombre CHECK (nombre IS NOT NULL)
);

-- Tabla de Estudiantes
CREATE TABLE ESTUDIANTES (
    id_estudiante NUMBER GENERATED BY DEFAULT AS IDENTITY,
    dni VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(150) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    correo VARCHAR2(150),
    telefono VARCHAR2(20),
    nacionalidad VARCHAR(50),
    id_centro NUMBER,
    titulacion VARCHAR2(150),
    curso_academico VARCHAR2(50),
    CONSTRAINT pk_estudiantes PRIMARY KEY (id_estudiante),
    CONSTRAINT uk_estudiantes_dni UNIQUE (dni),
    CONSTRAINT nn_estudiantes_dni CHECK (dni IS NOT NULL),
    CONSTRAINT nn_estudiantes_nombre CHECK (nombre IS NOT NULL),
    CONSTRAINT fk_estudiantes_centro FOREIGN KEY (id_centro) 
        REFERENCES CENTROS_EDUCATIVOS(id_centro) ON DELETE SET NULL
);

-- Tabla de Tutores
CREATE TABLE TUTORES (
    id_tutor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(150) NOT NULL,
    correo VARCHAR2(150),
    id_centro NUMBER,
    especialidad VARCHAR2(150),
    CONSTRAINT pk_tutores PRIMARY KEY (id_tutor),
    CONSTRAINT nn_tutores_nombre CHECK (nombre IS NOT NULL),
    CONSTRAINT fk_tutores_centro FOREIGN KEY (id_centro) 
        REFERENCES CENTROS_EDUCATIVOS(id_centro) ON DELETE SET NULL
);

-- Tabla de Empresas
CREATE TABLE EMPRESAS (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(150) NOT NULL,
    sector VARCHAR2(100),
    direccion VARCHAR2(255),
    ciudad VARCHAR2(100),
    persona_contacto VARCHAR2(150),
    correo_contacto VARCHAR2(150),
    telefono_contacto VARCHAR2(50),
    satisfaccion_media NUMBER(4,2),
    CONSTRAINT pk_empresas PRIMARY KEY (id_empresa),
    CONSTRAINT nn_empresas_nombre CHECK (nombre IS NOT NULL)
);

-- Tabla de Convenios
CREATE TABLE CONVENIOS (
    id_convenio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_empresa NUMBER NOT NULL,
    id_centro NUMBER NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    observaciones CLOB,
    CONSTRAINT pk_convenios PRIMARY KEY (id_convenio),
    CONSTRAINT nn_convenios_empresa CHECK (id_empresa IS NOT NULL),
    CONSTRAINT nn_convenios_centro CHECK (id_centro IS NOT NULL),
    CONSTRAINT fk_convenios_empresa FOREIGN KEY (id_empresa)
        REFERENCES EMPRESAS(id_empresa) ON DELETE CASCADE,
    CONSTRAINT fk_convenios_centro FOREIGN KEY (id_centro)
        REFERENCES CENTROS_EDUCATIVOS(id_centro) ON DELETE CASCADE
);

-- Tabla de Prácticas
CREATE TABLE PRACTICAS (
    id_practica NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_estudiante NUMBER NOT NULL,
    id_tutor NUMBER,
    id_empresa NUMBER NOT NULL,
    id_convenio NUMBER NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    horas_totales NUMBER,
    estado VARCHAR2(20),
    evaluacion_final NUMBER(4,2),
    CONSTRAINT pk_practicas PRIMARY KEY (id_practica),
    CONSTRAINT nn_practicas_estudiante CHECK (id_estudiante IS NOT NULL),
    CONSTRAINT nn_practicas_empresa CHECK (id_empresa IS NOT NULL),
    CONSTRAINT nn_practicas_convenio CHECK (id_convenio IS NOT NULL),
    CONSTRAINT ck_practicas_estado CHECK (estado IN ('pendiente','en curso','finalizada','cancelada')),
    CONSTRAINT fk_practicas_estudiante FOREIGN KEY (id_estudiante)
        REFERENCES ESTUDIANTES(id_estudiante) ON DELETE CASCADE,
    CONSTRAINT fk_practicas_tutor FOREIGN KEY (id_tutor)
        REFERENCES TUTORES(id_tutor) ON DELETE SET NULL,
    CONSTRAINT fk_practicas_empresa FOREIGN KEY (id_empresa)
        REFERENCES EMPRESAS(id_empresa) ON DELETE CASCADE,
    CONSTRAINT fk_practicas_convenio FOREIGN KEY (id_convenio)
        REFERENCES CONVENIOS(id_convenio) ON DELETE CASCADE
);

-- Tabla de Registros de Actividad
CREATE TABLE REGISTROS_ACTIVIDAD (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_practica NUMBER NOT NULL,
    fecha DATE NOT NULL,
    descripcion CLOB,
    horas NUMBER,
    validado_por_tutor CHAR(1),
    CONSTRAINT pk_registros_actividad PRIMARY KEY (id_registro),
    CONSTRAINT nn_registros_practica CHECK (id_practica IS NOT NULL),
    CONSTRAINT nn_registros_fecha CHECK (fecha IS NOT NULL),
    CONSTRAINT ck_registros_validado CHECK (validado_por_tutor IN ('0','1')),
    CONSTRAINT fk_registros_practica FOREIGN KEY (id_practica)
        REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
);

-- Tabla de Evaluaciones
CREATE TABLE EVALUACIONES (
    id_evaluacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_practica NUMBER NOT NULL,
    tipo VARCHAR2(50),
    fecha DATE,
    puntuacion NUMBER(4,2),
    comentarios CLOB,
    CONSTRAINT pk_evaluaciones PRIMARY KEY (id_evaluacion),
    CONSTRAINT nn_evaluaciones_practica CHECK (id_practica IS NOT NULL),
    CONSTRAINT ck_evaluaciones_tipo CHECK (tipo IN ('intermedia','final')),
    CONSTRAINT fk_evaluaciones_practica FOREIGN KEY (id_practica)
        REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
);

-- Tabla de Incidencias
CREATE TABLE INCIDENCIAS (
    id_incidencia NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_practica NUMBER NOT NULL,
    fecha DATE,
    descripcion CLOB,
    tipo VARCHAR2(50),
    resuelta CHAR(1),
    CONSTRAINT pk_incidencias PRIMARY KEY (id_incidencia),
    CONSTRAINT nn_incidencias_practica CHECK (id_practica IS NOT NULL),
    CONSTRAINT ck_incidencias_tipo CHECK (tipo IN ('leve','moderada','grave')),
    CONSTRAINT ck_incidencias_resuelta CHECK (resuelta IN ('0','1')),
    CONSTRAINT fk_incidencias_practica FOREIGN KEY (id_practica)
        REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
);

-- Tabla de Documentos
CREATE TABLE DOCUMENTOS (
    id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_practica NUMBER NOT NULL,
    tipo VARCHAR2(50),
    nombre_archivo VARCHAR2(255),
    ruta_archivo VARCHAR2(400),
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tamaño NUMBER(20),
    CONSTRAINT pk_documentos PRIMARY KEY (id_documento),
    CONSTRAINT nn_documentos_practica CHECK (id_practica IS NOT NULL),
    CONSTRAINT ck_documentos_tipo CHECK (tipo IN ('informe','anexo','evaluacion','otro')),
    CONSTRAINT fk_documentos_practica FOREIGN KEY (id_practica)
        REFERENCES PRACTICAS(id_practica) ON DELETE CASCADE
);

-- Tabla de Indicadores Analíticos
CREATE TABLE INDICADORES_ANALITICOS (
    id_indicador NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_empresa NUMBER,
    id_centro NUMBER,
    anio NUMBER(4),
    practicas_realizadas NUMBER,
    tasa_finalizacion NUMBER(5,2),
    satisfaccion_media NUMBER(5,2),
    tasa_contratacion NUMBER(5,2),
    abandonos NUMBER,
    CONSTRAINT pk_indicadores_analiticos PRIMARY KEY (id_indicador),
    CONSTRAINT fk_indicadores_empresa FOREIGN KEY (id_empresa)
        REFERENCES EMPRESAS(id_empresa) ON DELETE SET NULL,
    CONSTRAINT fk_indicadores_centro FOREIGN KEY (id_centro)
        REFERENCES CENTROS_EDUCATIVOS(id_centro) ON DELETE SET NULL
);

-- Tabla de Logs del Sistema
CREATE TABLE LOGS_SISTEMA (
    id_log NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER,
    tipo_evento VARCHAR2(100),
    fecha_evento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detalle CLOB,
    ip VARCHAR2(50),
    CONSTRAINT pk_logs_sistema PRIMARY KEY (id_log)
);

-- ============================================
-- ✅ FIN DEL SCRIPT
-- ============================================